name: Check
run-name: Check has started by ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
permissions:
  pull-requests: read
env:
  JAVA_VERSION: 17
jobs:
  checks:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          cache: 'gradle'
      - name: Check lint
        run: ./gradlew lint
      - name: Check projects
        run: ./gradlew check
